services:
    mariadb-test:
        image: mariadb:lts
        restart: always
        container_name: mariadb_db_test
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
        environment:
            MARIADB_USER: ${TEST_DB_USER}
            MARIADB_PASSWORD: ${TEST_DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD_TEST}
            MARIADB_DATABASE: ${TEST_DB_NAME}
        ports:
            - "3306:3306"
        volumes:
            - test_db_data:/var/lib/mysql
        command:
            [
                "--bind-address=0.0.0.0",
                "--innodb-flush-method=O_DIRECT",
                "--skip-innodb-use-native-aio",
            ]

volumes:
    test_db_data:
