services:
    db:
        image: mariadb:lts
        restart: always
        container_name: spe-db
        ports:
            - "3310:3306"
        volumes:
            - mariadb-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_NAME}
        networks:
            - prontuario_network

    api:
        build: .
        restart: always
        container_name: spe-api
        ports:
            - "3003:3003"
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_HOST: db
            DB_PORT: ${MARIADB_PORT}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            JWT_SECRET: ${JWT_SECRET}
        networks:
            - prontuario_network

volumes:
    mariadb-data:

networks:
    prontuario_network:
