export const CONTROLLER_TYPES = {
    LoginController: Symbol.for("LoginController"),
    CreatePatientController: Symbol.for("CreatePatientController"),
    ListPatientsController: Symbol.for("ListPatientsController"),
    UpdatePatientController: Symbol.for("UpdatePatientController"),
    DeletePatientController: Symbol.for("DeletePatientController"),
    CreateProfessionalController: Symbol.for("CreateProfessionalController"),
    ListProfessionalsController: Symbol.for("ListProfessionalsController"),
    CreateReceptionistController: Symbol.for("CreateReceptionistController"),
    CreateBookingController: Symbol.for("CreateBookingController"),
    ListBookingsController: Symbol.for("ListBookingsController"),
    UpdateBookingController: Symbol.for("UpdateBookingController"),
    DeleteBookingController: Symbol.for("DeleteBookingController"),
    CreateNurseController: Symbol.for("CreateNurseController"),
    ListNurseController: Symbol.for("ListNurseController"),
};
